/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAdminCheckRouteImport } from './routes/api/admin/check'
import { Route as ApiAdminDataRouteImport } from './routes/api/admin/data'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminResumeRouteImport } from './routes/api/admin/resume'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCheckRoute = ApiAdminCheckRouteImport.update({
  id: '/api/admin/check',
  path: '/api/admin/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDataRoute = ApiAdminDataRouteImport.update({
  id: '/api/admin/data',
  path: '/api/admin/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminResumeRoute = ApiAdminResumeRouteImport.update({
  id: '/api/admin/resume',
  path: '/api/admin/resume',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/check': typeof ApiAdminCheckRoute
  '/api/admin/data': typeof ApiAdminDataRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/resume': typeof ApiAdminResumeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/check': typeof ApiAdminCheckRoute
  '/api/admin/data': typeof ApiAdminDataRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/resume': typeof ApiAdminResumeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/check': typeof ApiAdminCheckRoute
  '/api/admin/data': typeof ApiAdminDataRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/resume': typeof ApiAdminResumeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/login'
    | '/api/chat'
    | '/api/health'
    | '/admin/'
    | '/api/admin/check'
    | '/api/admin/data'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/resume'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/api/chat'
    | '/api/health'
    | '/admin'
    | '/api/admin/check'
    | '/api/admin/data'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/resume'
  id:
    | '__root__'
    | '/'
    | '/admin/login'
    | '/api/chat'
    | '/api/health'
    | '/admin/'
    | '/api/admin/check'
    | '/api/admin/data'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/resume'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAdminCheckRoute: typeof ApiAdminCheckRoute
  ApiAdminDataRoute: typeof ApiAdminDataRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminResumeRoute: typeof ApiAdminResumeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/check': {
      id: '/api/admin/check'
      path: '/api/admin/check'
      fullPath: '/api/admin/check'
      preLoaderRoute: typeof ApiAdminCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/data': {
      id: '/api/admin/data'
      path: '/api/admin/data'
      fullPath: '/api/admin/data'
      preLoaderRoute: typeof ApiAdminDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/resume': {
      id: '/api/admin/resume'
      path: '/api/admin/resume'
      fullPath: '/api/admin/resume'
      preLoaderRoute: typeof ApiAdminResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHealthRoute: ApiHealthRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAdminCheckRoute: ApiAdminCheckRoute,
  ApiAdminDataRoute: ApiAdminDataRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminResumeRoute: ApiAdminResumeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
